spring:
  application:
    name: camunda-demo
  jackson:
    #设置返回前端的参数为驼峰的转换形式
    property-naming-strategy: SNAKE_CASE
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cam2?serverTimezone=Asia/Shanghai
    username: root
    password: root123


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

camunda:
  bpm:
    #配置账户密码来访问Camunda自带的管理界面

    admin-user:
      id: kermit
      password: superSecret
      first-name: kermit
    filter:
      create: All tasks
    #指定数据库类型
    database:
      type: mysql

      # false：       默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。（生产环境常用）
      # true：        activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。（开发时常用）
      # create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。（单元测试常用）
      # drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。

      schema-update: false
    #禁止自动部署resources下面的bpmn文件
    auto-deployment-enabled: false

    #禁止index跳转到Camunda自带的管理界面，默认true
#    webapp:
#      index-redirect-enabled: false

logging:
  level:
    org.camunda.bpm.engine: debug
