package org.hgq.domain.base;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CollectionLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public CollectionLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdIsNull() {
            addCriterion("collection_case_id is null");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdIsNotNull() {
            addCriterion("collection_case_id is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdEqualTo(String value) {
            addCriterion("collection_case_id =", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdNotEqualTo(String value) {
            addCriterion("collection_case_id <>", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdGreaterThan(String value) {
            addCriterion("collection_case_id >", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("collection_case_id >=", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdLessThan(String value) {
            addCriterion("collection_case_id <", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdLessThanOrEqualTo(String value) {
            addCriterion("collection_case_id <=", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdLike(String value) {
            addCriterion("collection_case_id like", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdNotLike(String value) {
            addCriterion("collection_case_id not like", value, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdIn(List<String> values) {
            addCriterion("collection_case_id in", values, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdNotIn(List<String> values) {
            addCriterion("collection_case_id not in", values, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdBetween(String value1, String value2) {
            addCriterion("collection_case_id between", value1, value2, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionCaseIdNotBetween(String value1, String value2) {
            addCriterion("collection_case_id not between", value1, value2, "collectionCaseId");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectIsNull() {
            addCriterion("collection_object is null");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectIsNotNull() {
            addCriterion("collection_object is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectEqualTo(Byte value) {
            addCriterion("collection_object =", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectNotEqualTo(Byte value) {
            addCriterion("collection_object <>", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectGreaterThan(Byte value) {
            addCriterion("collection_object >", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectGreaterThanOrEqualTo(Byte value) {
            addCriterion("collection_object >=", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectLessThan(Byte value) {
            addCriterion("collection_object <", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectLessThanOrEqualTo(Byte value) {
            addCriterion("collection_object <=", value, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectIn(List<Byte> values) {
            addCriterion("collection_object in", values, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectNotIn(List<Byte> values) {
            addCriterion("collection_object not in", values, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectBetween(Byte value1, Byte value2) {
            addCriterion("collection_object between", value1, value2, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCollectionObjectNotBetween(Byte value1, Byte value2) {
            addCriterion("collection_object not between", value1, value2, "collectionObject");
            return (Criteria) this;
        }

        public Criteria andCallWayIsNull() {
            addCriterion("call_way is null");
            return (Criteria) this;
        }

        public Criteria andCallWayIsNotNull() {
            addCriterion("call_way is not null");
            return (Criteria) this;
        }

        public Criteria andCallWayEqualTo(Byte value) {
            addCriterion("call_way =", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayNotEqualTo(Byte value) {
            addCriterion("call_way <>", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayGreaterThan(Byte value) {
            addCriterion("call_way >", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayGreaterThanOrEqualTo(Byte value) {
            addCriterion("call_way >=", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayLessThan(Byte value) {
            addCriterion("call_way <", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayLessThanOrEqualTo(Byte value) {
            addCriterion("call_way <=", value, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayIn(List<Byte> values) {
            addCriterion("call_way in", values, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayNotIn(List<Byte> values) {
            addCriterion("call_way not in", values, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayBetween(Byte value1, Byte value2) {
            addCriterion("call_way between", value1, value2, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallWayNotBetween(Byte value1, Byte value2) {
            addCriterion("call_way not between", value1, value2, "callWay");
            return (Criteria) this;
        }

        public Criteria andCallPhoneIsNull() {
            addCriterion("call_phone is null");
            return (Criteria) this;
        }

        public Criteria andCallPhoneIsNotNull() {
            addCriterion("call_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCallPhoneEqualTo(String value) {
            addCriterion("call_phone =", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneNotEqualTo(String value) {
            addCriterion("call_phone <>", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneGreaterThan(String value) {
            addCriterion("call_phone >", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("call_phone >=", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneLessThan(String value) {
            addCriterion("call_phone <", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneLessThanOrEqualTo(String value) {
            addCriterion("call_phone <=", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneLike(String value) {
            addCriterion("call_phone like", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneNotLike(String value) {
            addCriterion("call_phone not like", value, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneIn(List<String> values) {
            addCriterion("call_phone in", values, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneNotIn(List<String> values) {
            addCriterion("call_phone not in", values, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneBetween(String value1, String value2) {
            addCriterion("call_phone between", value1, value2, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallPhoneNotBetween(String value1, String value2) {
            addCriterion("call_phone not between", value1, value2, "callPhone");
            return (Criteria) this;
        }

        public Criteria andCallResultIsNull() {
            addCriterion("call_result is null");
            return (Criteria) this;
        }

        public Criteria andCallResultIsNotNull() {
            addCriterion("call_result is not null");
            return (Criteria) this;
        }

        public Criteria andCallResultEqualTo(Byte value) {
            addCriterion("call_result =", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultNotEqualTo(Byte value) {
            addCriterion("call_result <>", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultGreaterThan(Byte value) {
            addCriterion("call_result >", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultGreaterThanOrEqualTo(Byte value) {
            addCriterion("call_result >=", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultLessThan(Byte value) {
            addCriterion("call_result <", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultLessThanOrEqualTo(Byte value) {
            addCriterion("call_result <=", value, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultIn(List<Byte> values) {
            addCriterion("call_result in", values, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultNotIn(List<Byte> values) {
            addCriterion("call_result not in", values, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultBetween(Byte value1, Byte value2) {
            addCriterion("call_result between", value1, value2, "callResult");
            return (Criteria) this;
        }

        public Criteria andCallResultNotBetween(Byte value1, Byte value2) {
            addCriterion("call_result not between", value1, value2, "callResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultIsNull() {
            addCriterion("collection_result is null");
            return (Criteria) this;
        }

        public Criteria andCollectionResultIsNotNull() {
            addCriterion("collection_result is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionResultEqualTo(Byte value) {
            addCriterion("collection_result =", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultNotEqualTo(Byte value) {
            addCriterion("collection_result <>", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultGreaterThan(Byte value) {
            addCriterion("collection_result >", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultGreaterThanOrEqualTo(Byte value) {
            addCriterion("collection_result >=", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultLessThan(Byte value) {
            addCriterion("collection_result <", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultLessThanOrEqualTo(Byte value) {
            addCriterion("collection_result <=", value, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultIn(List<Byte> values) {
            addCriterion("collection_result in", values, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultNotIn(List<Byte> values) {
            addCriterion("collection_result not in", values, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultBetween(Byte value1, Byte value2) {
            addCriterion("collection_result between", value1, value2, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andCollectionResultNotBetween(Byte value1, Byte value2) {
            addCriterion("collection_result not between", value1, value2, "collectionResult");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateIsNull() {
            addCriterion("promise_repay_date is null");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateIsNotNull() {
            addCriterion("promise_repay_date is not null");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateEqualTo(Date value) {
            addCriterion("promise_repay_date =", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateNotEqualTo(Date value) {
            addCriterion("promise_repay_date <>", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateGreaterThan(Date value) {
            addCriterion("promise_repay_date >", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateGreaterThanOrEqualTo(Date value) {
            addCriterion("promise_repay_date >=", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateLessThan(Date value) {
            addCriterion("promise_repay_date <", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateLessThanOrEqualTo(Date value) {
            addCriterion("promise_repay_date <=", value, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateIn(List<Date> values) {
            addCriterion("promise_repay_date in", values, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateNotIn(List<Date> values) {
            addCriterion("promise_repay_date not in", values, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateBetween(Date value1, Date value2) {
            addCriterion("promise_repay_date between", value1, value2, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayDateNotBetween(Date value1, Date value2) {
            addCriterion("promise_repay_date not between", value1, value2, "promiseRepayDate");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountIsNull() {
            addCriterion("promise_repay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountIsNotNull() {
            addCriterion("promise_repay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountEqualTo(BigDecimal value) {
            addCriterion("promise_repay_amount =", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountNotEqualTo(BigDecimal value) {
            addCriterion("promise_repay_amount <>", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountGreaterThan(BigDecimal value) {
            addCriterion("promise_repay_amount >", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("promise_repay_amount >=", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountLessThan(BigDecimal value) {
            addCriterion("promise_repay_amount <", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("promise_repay_amount <=", value, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountIn(List<BigDecimal> values) {
            addCriterion("promise_repay_amount in", values, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountNotIn(List<BigDecimal> values) {
            addCriterion("promise_repay_amount not in", values, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promise_repay_amount between", value1, value2, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andPromiseRepayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promise_repay_amount not between", value1, value2, "promiseRepayAmount");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNull() {
            addCriterion("call_time is null");
            return (Criteria) this;
        }

        public Criteria andCallTimeIsNotNull() {
            addCriterion("call_time is not null");
            return (Criteria) this;
        }

        public Criteria andCallTimeEqualTo(Instant value) {
            addCriterion("call_time =", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotEqualTo(Instant value) {
            addCriterion("call_time <>", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThan(Instant value) {
            addCriterion("call_time >", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeGreaterThanOrEqualTo(Instant value) {
            addCriterion("call_time >=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThan(Instant value) {
            addCriterion("call_time <", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeLessThanOrEqualTo(Instant value) {
            addCriterion("call_time <=", value, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeIn(List<Instant> values) {
            addCriterion("call_time in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotIn(List<Instant> values) {
            addCriterion("call_time not in", values, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeBetween(Instant value1, Instant value2) {
            addCriterion("call_time between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallTimeNotBetween(Instant value1, Instant value2) {
            addCriterion("call_time not between", value1, value2, "callTime");
            return (Criteria) this;
        }

        public Criteria andCallDurationIsNull() {
            addCriterion("call_duration is null");
            return (Criteria) this;
        }

        public Criteria andCallDurationIsNotNull() {
            addCriterion("call_duration is not null");
            return (Criteria) this;
        }

        public Criteria andCallDurationEqualTo(Integer value) {
            addCriterion("call_duration =", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationNotEqualTo(Integer value) {
            addCriterion("call_duration <>", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationGreaterThan(Integer value) {
            addCriterion("call_duration >", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("call_duration >=", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationLessThan(Integer value) {
            addCriterion("call_duration <", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationLessThanOrEqualTo(Integer value) {
            addCriterion("call_duration <=", value, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationIn(List<Integer> values) {
            addCriterion("call_duration in", values, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationNotIn(List<Integer> values) {
            addCriterion("call_duration not in", values, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationBetween(Integer value1, Integer value2) {
            addCriterion("call_duration between", value1, value2, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("call_duration not between", value1, value2, "callDuration");
            return (Criteria) this;
        }

        public Criteria andCallRecordingIsNull() {
            addCriterion("call_recording is null");
            return (Criteria) this;
        }

        public Criteria andCallRecordingIsNotNull() {
            addCriterion("call_recording is not null");
            return (Criteria) this;
        }

        public Criteria andCallRecordingEqualTo(String value) {
            addCriterion("call_recording =", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingNotEqualTo(String value) {
            addCriterion("call_recording <>", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingGreaterThan(String value) {
            addCriterion("call_recording >", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingGreaterThanOrEqualTo(String value) {
            addCriterion("call_recording >=", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingLessThan(String value) {
            addCriterion("call_recording <", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingLessThanOrEqualTo(String value) {
            addCriterion("call_recording <=", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingLike(String value) {
            addCriterion("call_recording like", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingNotLike(String value) {
            addCriterion("call_recording not like", value, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingIn(List<String> values) {
            addCriterion("call_recording in", values, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingNotIn(List<String> values) {
            addCriterion("call_recording not in", values, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingBetween(String value1, String value2) {
            addCriterion("call_recording between", value1, value2, "callRecording");
            return (Criteria) this;
        }

        public Criteria andCallRecordingNotBetween(String value1, String value2) {
            addCriterion("call_recording not between", value1, value2, "callRecording");
            return (Criteria) this;
        }

        public Criteria andEmpNoIsNull() {
            addCriterion("emp_no is null");
            return (Criteria) this;
        }

        public Criteria andEmpNoIsNotNull() {
            addCriterion("emp_no is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNoEqualTo(String value) {
            addCriterion("emp_no =", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotEqualTo(String value) {
            addCriterion("emp_no <>", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoGreaterThan(String value) {
            addCriterion("emp_no >", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoGreaterThanOrEqualTo(String value) {
            addCriterion("emp_no >=", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoLessThan(String value) {
            addCriterion("emp_no <", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoLessThanOrEqualTo(String value) {
            addCriterion("emp_no <=", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoLike(String value) {
            addCriterion("emp_no like", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotLike(String value) {
            addCriterion("emp_no not like", value, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoIn(List<String> values) {
            addCriterion("emp_no in", values, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotIn(List<String> values) {
            addCriterion("emp_no not in", values, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoBetween(String value1, String value2) {
            addCriterion("emp_no between", value1, value2, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNoNotBetween(String value1, String value2) {
            addCriterion("emp_no not between", value1, value2, "empNo");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("emp_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("emp_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("emp_NAME =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("emp_NAME <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("emp_NAME >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_NAME >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("emp_NAME <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("emp_NAME <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("emp_NAME like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("emp_NAME not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("emp_NAME in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("emp_NAME not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("emp_NAME between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("emp_NAME not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Instant value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Instant value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Instant value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Instant value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Instant value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Instant value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Instant> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Instant> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Instant value1, Instant value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Instant value1, Instant value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Instant value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Instant value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Instant value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Instant value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Instant value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Instant value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Instant> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Instant> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Instant value1, Instant value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Instant value1, Instant value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection_log
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 19 11:25:54 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collection_log
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}