package org.hgq.domain.base;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Date;

public class CollectionCase extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.user_no
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.user_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.product_source
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte productSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.product_code
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.overdue_days
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Integer overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.surplus_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private BigDecimal surplusAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.status
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.allocation_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant allocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.finish_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte talkResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.collection_log_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant collectionLogTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.process_instance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.performance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long performanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_case
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.id
     *
     * @return the value of collection_case.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.id
     *
     * @param id the value for collection_case.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.user_no
     *
     * @return the value of collection_case.user_no
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.user_no
     *
     * @param userNo the value for collection_case.user_no
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.user_id
     *
     * @return the value of collection_case.user_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.user_id
     *
     * @param userId the value for collection_case.user_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.product_source
     *
     * @return the value of collection_case.product_source
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getProductSource() {
        return productSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.product_source
     *
     * @param productSource the value for collection_case.product_source
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setProductSource(Byte productSource) {
        this.productSource = productSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.product_code
     *
     * @return the value of collection_case.product_code
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.product_code
     *
     * @param productCode the value for collection_case.product_code
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.overdue_days
     *
     * @return the value of collection_case.overdue_days
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.overdue_days
     *
     * @param overdueDays the value for collection_case.overdue_days
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.amount
     *
     * @return the value of collection_case.amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.amount
     *
     * @param amount the value for collection_case.amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.surplus_amount
     *
     * @return the value of collection_case.surplus_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public BigDecimal getSurplusAmount() {
        return surplusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.surplus_amount
     *
     * @param surplusAmount the value for collection_case.surplus_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setSurplusAmount(BigDecimal surplusAmount) {
        this.surplusAmount = surplusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.status
     *
     * @return the value of collection_case.status
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.status
     *
     * @param status the value for collection_case.status
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.allocation_time
     *
     * @return the value of collection_case.allocation_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.allocation_time
     *
     * @param allocationTime the value for collection_case.allocation_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setAllocationTime(Instant allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.finish_time
     *
     * @return the value of collection_case.finish_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.finish_time
     *
     * @param finishTime the value for collection_case.finish_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.emp_id
     *
     * @return the value of collection_case.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.emp_id
     *
     * @param empId the value for collection_case.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.talk_result
     *
     * @return the value of collection_case.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getTalkResult() {
        return talkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.talk_result
     *
     * @param talkResult the value for collection_case.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setTalkResult(Byte talkResult) {
        this.talkResult = talkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.collection_log_time
     *
     * @return the value of collection_case.collection_log_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getCollectionLogTime() {
        return collectionLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.collection_log_time
     *
     * @param collectionLogTime the value for collection_case.collection_log_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCollectionLogTime(Instant collectionLogTime) {
        this.collectionLogTime = collectionLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.process_instance_id
     *
     * @return the value of collection_case.process_instance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.process_instance_id
     *
     * @param processInstanceId the value for collection_case.process_instance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.performance_id
     *
     * @return the value of collection_case.performance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getPerformanceId() {
        return performanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.performance_id
     *
     * @param performanceId the value for collection_case.performance_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setPerformanceId(Long performanceId) {
        this.performanceId = performanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.remark
     *
     * @return the value of collection_case.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.remark
     *
     * @param remark the value for collection_case.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.version
     *
     * @return the value of collection_case.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.version
     *
     * @param version the value for collection_case.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.deleted
     *
     * @return the value of collection_case.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.deleted
     *
     * @param deleted the value for collection_case.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.create_time
     *
     * @return the value of collection_case.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.create_time
     *
     * @param createTime the value for collection_case.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCreateTime(Instant createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.update_time
     *
     * @return the value of collection_case.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.update_time
     *
     * @param updateTime the value for collection_case.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setUpdateTime(Instant updateTime) {
        this.updateTime = updateTime;
    }
}