package org.hgq.domain.base;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Date;

public class CollectionLog extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.collection_case_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long collectionCaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.collection_object
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte collectionObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_way
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte callWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_phone
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String callPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte callResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Byte talkResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.promise_repay_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Date promiseRepayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.promise_repay_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private BigDecimal promiseRepayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant callTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_duration
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Integer callDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.call_recording
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String callRecording;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.emp_NAME
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_log.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private Instant updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_log
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.id
     *
     * @return the value of collection_log.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.id
     *
     * @param id the value for collection_log.id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.collection_case_id
     *
     * @return the value of collection_log.collection_case_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getCollectionCaseId() {
        return collectionCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.collection_case_id
     *
     * @param collectionCaseId the value for collection_log.collection_case_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCollectionCaseId(Long collectionCaseId) {
        this.collectionCaseId = collectionCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.collection_object
     *
     * @return the value of collection_log.collection_object
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getCollectionObject() {
        return collectionObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.collection_object
     *
     * @param collectionObject the value for collection_log.collection_object
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCollectionObject(Byte collectionObject) {
        this.collectionObject = collectionObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_way
     *
     * @return the value of collection_log.call_way
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getCallWay() {
        return callWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_way
     *
     * @param callWay the value for collection_log.call_way
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallWay(Byte callWay) {
        this.callWay = callWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_phone
     *
     * @return the value of collection_log.call_phone
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getCallPhone() {
        return callPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_phone
     *
     * @param callPhone the value for collection_log.call_phone
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallPhone(String callPhone) {
        this.callPhone = callPhone == null ? null : callPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_result
     *
     * @return the value of collection_log.call_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getCallResult() {
        return callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_result
     *
     * @param callResult the value for collection_log.call_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallResult(Byte callResult) {
        this.callResult = callResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.talk_result
     *
     * @return the value of collection_log.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Byte getTalkResult() {
        return talkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.talk_result
     *
     * @param talkResult the value for collection_log.talk_result
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setTalkResult(Byte talkResult) {
        this.talkResult = talkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.promise_repay_time
     *
     * @return the value of collection_log.promise_repay_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Date getPromiseRepayTime() {
        return promiseRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.promise_repay_time
     *
     * @param promiseRepayTime the value for collection_log.promise_repay_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setPromiseRepayTime(Date promiseRepayTime) {
        this.promiseRepayTime = promiseRepayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.promise_repay_amount
     *
     * @return the value of collection_log.promise_repay_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public BigDecimal getPromiseRepayAmount() {
        return promiseRepayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.promise_repay_amount
     *
     * @param promiseRepayAmount the value for collection_log.promise_repay_amount
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setPromiseRepayAmount(BigDecimal promiseRepayAmount) {
        this.promiseRepayAmount = promiseRepayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_time
     *
     * @return the value of collection_log.call_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_time
     *
     * @param callTime the value for collection_log.call_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallTime(Instant callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_duration
     *
     * @return the value of collection_log.call_duration
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Integer getCallDuration() {
        return callDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_duration
     *
     * @param callDuration the value for collection_log.call_duration
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallDuration(Integer callDuration) {
        this.callDuration = callDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.call_recording
     *
     * @return the value of collection_log.call_recording
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getCallRecording() {
        return callRecording;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.call_recording
     *
     * @param callRecording the value for collection_log.call_recording
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCallRecording(String callRecording) {
        this.callRecording = callRecording == null ? null : callRecording.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.emp_id
     *
     * @return the value of collection_log.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.emp_id
     *
     * @param empId the value for collection_log.emp_id
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.emp_NAME
     *
     * @return the value of collection_log.emp_NAME
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.emp_NAME
     *
     * @param empName the value for collection_log.emp_NAME
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.remark
     *
     * @return the value of collection_log.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.remark
     *
     * @param remark the value for collection_log.remark
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.version
     *
     * @return the value of collection_log.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.version
     *
     * @param version the value for collection_log.version
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.deleted
     *
     * @return the value of collection_log.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.deleted
     *
     * @param deleted the value for collection_log.deleted
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.create_time
     *
     * @return the value of collection_log.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.create_time
     *
     * @param createTime the value for collection_log.create_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setCreateTime(Instant createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_log.update_time
     *
     * @return the value of collection_log.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public Instant getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_log.update_time
     *
     * @param updateTime the value for collection_log.update_time
     *
     * @mbg.generated Sat Sep 04 11:19:13 CST 2021
     */
    public void setUpdateTime(Instant updateTime) {
        this.updateTime = updateTime;
    }
}