package org.hgq.domain.base;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

public class CollectionCase extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.user_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.user_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.id_card
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.mobile
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.case_source
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Byte caseSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.product_code
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.overdue_days
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Integer overdueDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.debt_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private BigDecimal debtAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.deferrable_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private BigDecimal deferrableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.lifecycle
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Byte lifecycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.allocation_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Instant allocationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.group_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String groupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.group_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.emp_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.emp_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.collection_result
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Byte collectionResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.collection_log_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Instant collectionLogTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.process_instance_id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String processInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.remark
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.version
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.deleted
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.create_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Instant createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_case.update_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private Instant updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection_case
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.id
     *
     * @return the value of collection_case.id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.id
     *
     * @param id the value for collection_case.id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.user_no
     *
     * @return the value of collection_case.user_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.user_no
     *
     * @param userNo the value for collection_case.user_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.user_name
     *
     * @return the value of collection_case.user_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.user_name
     *
     * @param userName the value for collection_case.user_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.id_card
     *
     * @return the value of collection_case.id_card
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.id_card
     *
     * @param idCard the value for collection_case.id_card
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.mobile
     *
     * @return the value of collection_case.mobile
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.mobile
     *
     * @param mobile the value for collection_case.mobile
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.case_source
     *
     * @return the value of collection_case.case_source
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Byte getCaseSource() {
        return caseSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.case_source
     *
     * @param caseSource the value for collection_case.case_source
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setCaseSource(Byte caseSource) {
        this.caseSource = caseSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.product_code
     *
     * @return the value of collection_case.product_code
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.product_code
     *
     * @param productCode the value for collection_case.product_code
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.overdue_days
     *
     * @return the value of collection_case.overdue_days
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Integer getOverdueDays() {
        return overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.overdue_days
     *
     * @param overdueDays the value for collection_case.overdue_days
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setOverdueDays(Integer overdueDays) {
        this.overdueDays = overdueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.debt_amount
     *
     * @return the value of collection_case.debt_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public BigDecimal getDebtAmount() {
        return debtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.debt_amount
     *
     * @param debtAmount the value for collection_case.debt_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setDebtAmount(BigDecimal debtAmount) {
        this.debtAmount = debtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.deferrable_amount
     *
     * @return the value of collection_case.deferrable_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public BigDecimal getDeferrableAmount() {
        return deferrableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.deferrable_amount
     *
     * @param deferrableAmount the value for collection_case.deferrable_amount
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setDeferrableAmount(BigDecimal deferrableAmount) {
        this.deferrableAmount = deferrableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.lifecycle
     *
     * @return the value of collection_case.lifecycle
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Byte getLifecycle() {
        return lifecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.lifecycle
     *
     * @param lifecycle the value for collection_case.lifecycle
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setLifecycle(Byte lifecycle) {
        this.lifecycle = lifecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.allocation_time
     *
     * @return the value of collection_case.allocation_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Instant getAllocationTime() {
        return allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.allocation_time
     *
     * @param allocationTime the value for collection_case.allocation_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setAllocationTime(Instant allocationTime) {
        this.allocationTime = allocationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.group_no
     *
     * @return the value of collection_case.group_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.group_no
     *
     * @param groupNo the value for collection_case.group_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo == null ? null : groupNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.group_name
     *
     * @return the value of collection_case.group_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.group_name
     *
     * @param groupName the value for collection_case.group_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.emp_no
     *
     * @return the value of collection_case.emp_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.emp_no
     *
     * @param empNo the value for collection_case.emp_no
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setEmpNo(String empNo) {
        this.empNo = empNo == null ? null : empNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.emp_name
     *
     * @return the value of collection_case.emp_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.emp_name
     *
     * @param empName the value for collection_case.emp_name
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.collection_result
     *
     * @return the value of collection_case.collection_result
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Byte getCollectionResult() {
        return collectionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.collection_result
     *
     * @param collectionResult the value for collection_case.collection_result
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setCollectionResult(Byte collectionResult) {
        this.collectionResult = collectionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.collection_log_time
     *
     * @return the value of collection_case.collection_log_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Instant getCollectionLogTime() {
        return collectionLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.collection_log_time
     *
     * @param collectionLogTime the value for collection_case.collection_log_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setCollectionLogTime(Instant collectionLogTime) {
        this.collectionLogTime = collectionLogTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.process_instance_id
     *
     * @return the value of collection_case.process_instance_id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.process_instance_id
     *
     * @param processInstanceId the value for collection_case.process_instance_id
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId == null ? null : processInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.remark
     *
     * @return the value of collection_case.remark
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.remark
     *
     * @param remark the value for collection_case.remark
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.version
     *
     * @return the value of collection_case.version
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.version
     *
     * @param version the value for collection_case.version
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.deleted
     *
     * @return the value of collection_case.deleted
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.deleted
     *
     * @param deleted the value for collection_case.deleted
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.create_time
     *
     * @return the value of collection_case.create_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Instant getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.create_time
     *
     * @param createTime the value for collection_case.create_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setCreateTime(Instant createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_case.update_time
     *
     * @return the value of collection_case.update_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public Instant getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_case.update_time
     *
     * @param updateTime the value for collection_case.update_time
     *
     * @mbg.generated Thu Aug 19 11:25:54 CST 2021
     */
    public void setUpdateTime(Instant updateTime) {
        this.updateTime = updateTime;
    }
}